---
title: we are cast
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  content:
    title: content
    output: true
email: hello@wearecast.org.uk
description: second iteration of the cast website
baseurl: ''
url: https://techforgoodcast.github.io/cast-website2.0
markdown: kramdown
