title: we are cast
email: hello@wearecast.org.uk
description: >-
  second iteration of the cast website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
