---
title: we are cast
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@wearecast.org.uk
description: second iteration of the cast website
baseurl: ''
url: ''
markdown: kramdown
